from models.pessoa import Pessoa
from models.artista import Artista
from models.ator import Ator
from models.diretor import Diretor
from models.filme import Filme
from models.categoria import Categoria
from models.indicacao import Indicacao
from models.membro import Membro
from models.voto import Voto